trigger:
  - master
  - pr

pool:
  vmImage: 'VS2017-Win2016'

steps:
- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'Finsemble-Seed'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'Finsemble-Seed'
    cliProjectName: 'Finsemble-Seed'
    cliSources: '.'
- task: SonarQubeAnalyze@4
- task: SonarQubePublish@4
  inputs:
    pollingTimeoutSec: '300'
